name = "ok-library-api"
main = "src/index.ts"
compatibility_date = "2026-04-23"

[observability.logs]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "ok_library"
database_id = "55bc2aa5-fa61-4597-b47f-b645fba5ed44"
migrations_dir = "migrations"

[[kv_namespaces]]
binding = "CACHE"
id = "6faf64c9dffb407985dc58d180b4eb99"

[[r2_buckets]]
binding = "ASSETS"
bucket_name = "ok-library-assets"

[vars]
APP_ENV = "production"
JWT_ISSUER = "ok-library-api"
ACCESS_TOKEN_TTL_SECONDS = "43200"
CORS_ORIGIN = "*"
